[package]
authors = ["Keith Simmons <keith@the-simmons.net>"]
name = "vector-8"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
lyon = "0.14.1"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.5"
