[package]
authors = ["Keith Simmons <keith@the-simmons.net>"]
name = "vector-8"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "*"
lyon = "0.14.1"
wasm-bindgen = "0.2.5"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console'
]
